### ISSUE TITLE
nbecom new protocol?

### ISSUE THREAD

**Issue by e1z0** [motoz/PellMon#118]
Hi, i've got these errors:

```
find controller retry 0 protocol_error('wrong length',)
wait controller
wait controller
find controller retry 1 protocol_error('wrong length',)
wait controller
wait controller
find controller retry 2 protocol_error('wrong length',)
wait controller
wait controller
wait controller
wait controller
find controller retry 0 protocol_error('wrong length',)
wait controller
wait controller
find controller retry 1 protocol_error('wrong length',)
wait controller
wait controller
wait controller
find controller retry 2 protocol_error('wrong length',)
wait controller
wait controller
wait controller
wait controller

```
i've tried code from develop branch.
Current controller version: 13.1016.2
NBE Blackstar+

Maybe there are some incompatibilities with newest versions of controller?

**Comment by motoz** [comment]
If it's something small I might be able to do something if you could provide wireshark logs of the communication. It might be just the discovery frames that have  changed. Or something...

**Comment by e1z0** [comment]
I've attached the pcap file
[nbe_v13_protocol.pcap.zip](https://github.com/motoz/PellMon/files/7160588/nbe_v13_protocol.pcap.zip)

**Comment by motoz** [comment]
The frame payload in the discovery response from the controller starts at 0x2a here:
```
0000   e4 11 5b ce 23 f1 68 c6 3a dd bb 39 08 00 45 00   ..[.#.h.:..9..E.
0010   00 7f b1 9f 00 00 80 11 ed 12 c0 a8 0d 6a c0 a8   .............j..
0020   0d 01 21 23 21 24 00 6b 5f bc 17 49 55 30 39 25   ..!#!$.k_..IU09%
0030   5d 0b 5e 28 4a 22 30 35 35 31 31 36 02 30 30 37   ].^(J"055116.007
0040   39 30 30 30 36 36 20 20 20 20 53 65 72 69 61 6c   900066    Serial
0050   3d 35 35 31 31 36 3b 49 50 3d 31 39 32 2e 31 36   =55116;IP=192.16
0060   38 2e 31 33 2e 31 30 36 3b 54 79 70 65 3d 76 31   8.13.106;Type=v1
0070   33 73 74 64 3b 56 65 72 3d 31 30 31 36 3b 42 75   3std;Ver=1016;Bu
0080   69 6c 64 3d 32 3b 4c 61 6e 67 3d 30 04            ild=2;Lang=0.
```

There you can follow the decoding from here: https://github.com/motoz/PellMon/blob/7bb2e51c33376cb08a703035e539708a3c7024e0/src/Pellmonsrv/plugins/nbecom/nbeprotocol/frames.py#L152

It looks like the controller response with a "frame payload size = 66 bytes" and then it actually transmits 71 bytes, which the nbecom plugin doesn't like (what's the point of having payload size iin the frame header if you can't use it to detect an error in the frame?). Anyway, if you can run the code directly you can try to change this line: 

    if not len(record) == self.size + self.RESPONSE_HEADER_SIZE:

to for instance `if False:`

Then it will accept whatever size the controller responds with.

**Comment by motoz** [comment]
Oh, you'll need to remove this check also

    if not record[i] == END[0]:

since the end mark is in the wrong place also. The NBE app that talks to this version apparently ignores the size field in the header, otherwise it wouldn't work.

**Comment by e1z0** [comment]
Now i've got another error:

```
find controller retry 1 timeout('timed out',)
wait controller
wait controller
wait controller
find controller retry 2 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 0 timeout('timed out',)
wait controller
wait controller
find controller retry 1 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 2 timeout('timed out',)
wait controller
wait controller
wait controller
find controller retry 0 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
find controller retry 1 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
wait controller
find controller retry 2 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 0 timeout('timed out',)
wait controller
wait controller
find controller retry 1 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 2 timeout('timed out',)
wait controller
wait controller
wait controller
find controller retry 0 ValueError('need more than 1 value to unpack',)
wait controller
wait controller
wait controller
wait controller
wait controller
find controller retry 1 timeout('timed out',)
```

**Comment by motoz** [comment]
Strange, now it looks like you get no response (timeout). What does wireshark say?

**Comment by e1z0** [comment]
Attached the bcap :)
[nbe_v13_protocol.pcap.zip](https://github.com/motoz/PellMon/files/7169746/nbe_v13_protocol.pcap.zip)

**Comment by motoz** [comment]
So it's still the same response as last time, then I don't really have an explanation, sorry. You could try sprinkling some print statements between every row in the find_controller function to see more of what  happens and where.

**Comment by e1z0** [comment]
Hey motoz, i've got some progress and managed to retrieve the all available burner info via nbetest from your other repository, the only problem is the timeout, that occurs sometimes:

```
Traceback (most recent call last):
  File "/root/nbetest/client.py", line 81, in <module>
    args.func(args, proxy)
  File "/root/nbetest/client.py", line 27, in getfunc
    l = proxy.get(args.path)
  File "/root/nbetest/protocol.py", line 111, in get
    response = self.make_request(f, '*')
  File "/root/nbetest/protocol.py", line 175, in make_request
    data, server = self.s.recvfrom(4096)
socket.timeout: timed out
```

**Comment by e1z0** [comment]
I've got implemented some poll wait for make_request function in protocol.py

```
    def make_request(self, function, payload, encrypt=False, key=None):
        #print(' '.join([hex(ord(ch)) for ch in c.framedata]))
        self.request.sequencenumber += 1
        self.request.payload = payload
        self.request.function = function
        self.request.encrypted = encrypt
        self.request.pincode = self.password
        self.s.sendto(self.request.encode(), self.addr)
        # some timeout
        ready = select.select([self.s], [], [], 5)
        if ready[0]:
          data, server = self.s.recvfrom(4096)
          self.response.decode(data)
          return self.response
```

But i see that self.s.settimeout(5.0) does the job too and the time outs occurs much less, but anyway it occurs 1/20 times.

**Comment by e1z0** [comment]
Now i think it retrieves some data from pellet burner, i've tried to port as much same functionality from nbetest protocol as i can, but now get some other errors...

```
No option 'plugin_dirs' in section: 'plugin_settings'
/source/src/Pellmonsrv/plugins/calculate/__init__
/source/src/Pellmonsrv/plugins/cleaning/__init__
/source/src/Pellmonsrv/plugins/consumption/__init__
/source/src/Pellmonsrv/plugins/customalarms/__init__
/source/src/Pellmonsrv/plugins/exec/__init__
/source/src/Pellmonsrv/plugins/heatingcircuit/__init__
/source/src/Pellmonsrv/plugins/nbecom/__init__
/source/src/Pellmonsrv/plugins/onewire/__init__
/source/src/Pellmonsrv/plugins/openweathermap/__init__
/source/src/Pellmonsrv/plugins/owfs/__init__
/source/src/Pellmonsrv/plugins/pelletcalc/__init__
/source/src/Pellmonsrv/plugins/raspberrygpio/__init__
No module named RPi.GPIO
/source/src/Pellmonsrv/plugins/scottecom/__init__
/source/src/Pellmonsrv/plugins/silolevel/__init__
/source/src/Pellmonsrv/plugins/testplugin/__init__
/source/src/Pellmonsrv/plugins/mgm/__init__
Looking for controller with S/N 55116
received data:    ghkcggfcha05511600960059Serial=55116;IP=0.0.0.0;Type=v13std;Ver=1016;Build=2;Lang=0
got response:  {u'Lang': u'0', u'Ver': u'1016', u'IP': u'0.0.0.0', u'Build': u'2', u'Serial': u'55116', u'Type': u'v13std'}
got serial:  55116
get rsa 0
decode rsa key:  MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKr3EOhDukLH0syjRrMQ5iEBzrkOcM3NAcyz3n5Q2XdDSjxe5JT44cZqnbhN8RNHkONO7RcWv9Ytrg3lcJtiwwECAwEAAQ==
set xtea
use rsa for xtea set 3499
set value %tF-19H%Nj&"
wait controller
set error: 1
xtea_set uncertain, del key and use rsa 1632070702.3
use rsa for xtea set 3504
set value =.?eO
               V_J2+6B
set error: 1
xtea_set uncertain, del key and use rsa 1632070707.48
use rsa for xtea set 3508
set value %tF-19H%Nj&"
set error: 1
set retry 1 3512
xtea_set uncertain, del key and use rsa 1632070712.55
use rsa for xtea set 3512
set value =.?eO
               V_J2+6B
set error: 1
set retry 1 3515
xtea_set uncertain, del key and use rsa 1632070715.84
use rsa for xtea set 3516
set value %tF-19H%Nj&"
set error: 1
set retry 2 3519
xtea_set uncertain, del key and use rsa 1632070719.79
use rsa for xtea set 3520
set value =.?eO
               V_J2+6B
set error: 1
set retry 2 3524
xtea_set uncertain, del key and use rsa 1632070724.13
use rsa for xtea set 3524
set value %tF-19H%Nj&"
set error: 1
set retry 3 3527
xtea_set uncertain, del key and use rsa 1632070727.37
use rsa for xtea set 3528
set value =.?eO
               V_J2+6B
set error: 1
set retry 3 3531
xtea_set uncertain, del key and use rsa 1632070731.65
use rsa for xtea set 3532
set value %tF-19H%Nj&"
set error: 1
set retry 4 3536
xtea_set uncertain, del key and use rsa 1632070736.07
use rsa for xtea set 3536
set value =.?eO
               V_J2+6B
set error: 1
set retry 4 3539
xtea_set uncertain, del key and use rsa 1632070739.32
use rsa for xtea set 3539
set value %tF-19H%Nj&"
set error: 1
set retry 5 3543
xtea_set uncertain, del key and use rsa 1632070743.27
use rsa for xtea set 3544
set value =.?eO
               V_J2+6B
set error: 1
set retry 5 3547
xtea_set uncertain, del key and use rsa 1632070747.56
use rsa for xtea set 3548
set value %tF-19H%Nj&"
set error: 1
set retry 6 3551
xtea_set uncertain, del key and use rsa 1632070751.11
timeout, func: 4 missed seqnum: 29 3551
use rsa for xtea set 3551
set value =.?eO
               V_J2+6B
no more set retry
KeyError('oxygen-time',) exc in getgroup time 1632070756.57
KeyError('operating_data-regulation',) exc in getgroup regulation 1632070756.86
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/source/src/Pellmonsrv/plugins/nbecom/__init__.py", line 83, in <lambda>
    self.alarmthread = threading.Thread(target=lambda:self.alarm_poller())
  File "/source/src/Pellmonsrv/plugins/nbecom/__init__.py", line 257, in alarm_poller
    alarm = self.db['alarm'].value
  File "/source/src/Pellmonsrv/database.py", line 47, in value
    self._value = self.getter(self.name)
  File "/source/src/Pellmonsrv/plugins/nbecom/__init__.py", line 176, in <lambda>
    item = Getsetitem('alarm', None, getter=lambda i:get_combined_alarm_state())
  File "/source/src/Pellmonsrv/plugins/nbecom/__init__.py", line 171, in get_combined_alarm_state
    if int(self.db['operating_data-off_on_alarm'].value) >= 2:
  File "/source/src/Pellmonsrv/database.py", line 69, in value
    self.cached_value = self.getter(self.name)
  File "/source/src/Pellmonsrv/plugins/nbecom/__init__.py", line 123, in get_group
    i = self.db[n]
  File "/usr/lib/python2.7/weakref.py", line 83, in __getitem__
    o = self.data[key]()
KeyError: 'operating_data-regulation'

ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',) exc in getgroup fan-airflow_max 1632070757.68
 set value Mm)0g9tVI@=]=y|
xtea encrypt 1
xtea encrypt 2
received data:    ghkcggfcha05511601380152pellets=60.0;power=55;fan_10=40;fan_50=50;fan_100=60;max_time=5;preheat_time=30;exhaust_speed=30;ignition_number=347;clear_ignitions=0;flame_detection=0
got response:  {u'power': u'55', u'fan_50': u'50', u'clear_ignitions': u'0', u'flame_detection': u'0', u'fan_10': u'40', u'preheat_time': u'30', u'fan_100': u'60', u'max_time': u'5', u'pellets': u'60.0', u'exhaust_speed': u'30', u'ignition_number': u'347'}
got serial:  2find controller retry 0 KeyError('Serial',)
ValueError('need more than 1 value to unpack',)
KeyError('ignition-Serial',) exc in getgroup Serial 1632070758.6
KeyError('weather2-pellets',) exc in getgroup pellets 1632070758.83
ValueError('need more than 1 value to unpack',)
KeyError('manual-output_up',) exc in getgroup output_up 1632070759.52
KeyError('fan-manual_mode',) exc in getgroup manual_mode 1632070759.75
KeyError('auger-output_exhaust',) exc in getgroup output_exhaust 1632070759.99
KeyError('boiler-forced_run',) exc in getgroup forced_run 1632070760.12
KeyError('vacuum-temp',) exc in getgroup temp 1632070760.4
ValueError('need more than 1 value to unpack',)
received data:    ghkcggfcha05511601480585monday=000000000000000000000000;tuesday=000000000000000000000000;wednesday=000000000000000000000000;thursday=000000000000000000000000;friday=000000000000000000000000;saturday=000000000000000000000000;sunday=000000000000000000000000;allweek=000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000;output_auger=0;output_vacuum=0;dutycycle_auger=100;minutes_pr_cm=15;max_time_out_of_range=30;total_hours=0;clear_alarm=0;min_distance=20;max_distance=80;distance_sensor=0
got response:  {u'allweek': u'000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000', u'monday': u'000000000000000000000000', u'tuesday': u'000000000000000000000000', u'friday': u'000000000000000000000000', u'wednesday': u'000000000000000000000000', u'thursday': u'000000000000000000000000', u'clear_alarm': u'0', u'total_hours': u'0', u'sunday': u'000000000000000000000000', u'dutycycle_auger': u'100', u'output_auger': u'0', u'max_time_out_of_range': u'30', u'distance_sensor': u'0', u'max_distance': u'80', u'output_vacuum': u'0', u'minutes_pr_cm': u'15', u'saturday': u'000000000000000000000000', u'min_distance': u'20'}
got serial:  2find controller retry 1 KeyError('Serial',)
KeyError('operating_data-Serial',) exc in getgroup Serial 1632070760.89
ValueError('need more than 1 value to unpack',)
KeyError('boiler-time',) exc in getgroup time 1632070761.46
KeyError('auger-temp',) exc in getgroup temp 1632070761.67
KeyError('manual-forced_run',) exc in getgroup forced_run 1632070761.91
KeyError('auger-manual_mode',) exc in getgroup manual_mode 1632070762.12
KeyError('weather-forced_run',) exc in getgroup forced_run 1632070762.39
KeyError('auger-output_up',) exc in getgroup output_up 1632070762.67
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',) exc in getgroup fan-speed_10 1632070763.47
received data:    ghkcggfcha05511601590341output_exhaust=0;speed_10=17;speed_50=21;speed_100=23;use_fan_rpm=0;alarm_fan_rpm=0;alarm_fan_current=0;exhaust_10=15;exhaust_50=22;exhaust_100=27;airflow_10=10.0;airflow_50=22.0;airflow_100=45.0;airflow_max=300.0;airflow_cold_0=0;airflow_cold_100=0;airflow_warm_0=0;airflow_warm_100=0;airflow_reg_time=5;available=0;calibrated=0;calibrate=0
got response:  {u'airflow_max': u'300.0', u'alarm_fan_rpm': u'0', u'airflow_cold_0': u'0', u'airflow_cold_100': u'0', u'calibrate': u'0', u'speed_10': u'17', u'speed_50': u'21', u'exhaust_100': u'27', u'airflow_warm_0': u'0', u'exhaust_10': u'15', u'speed_100': u'23', u'airflow_50': u'22.0', u'available': u'0', u'airflow_10': u'10.0', u'exhaust_50': u'22', u'output_exhaust': u'0', u'airflow_reg_time': u'5', u'airflow_100': u'45.0', u'airflow_warm_100': u'0', u'alarm_fan_current': u'0', u'calibrated': u'0', u'use_fan_rpm': u'0'}
got serial:  2find controller retry 2 KeyError('Serial',)
set value q#dMq9{v_a,gM~)
xtea encrypt 1
xtea encrypt 2
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
-------------------lost conn
KeyError('hot_water-time',) exc in getgroup time 1632070765.95
ValueError('need more than 1 value to unpack',)
Looking for controller with S/N 55116
received data:    ghkcggfcha05511601640236temp=0;diff_under=10;dhw_remain=10;output=0;dwh_weather=0;dwh_weather2=0;timer=0;monday=000000000000;tuesday=000000000000;wednesday=000000000000;thursday=000000000000;friday=000000000000;saturday=000000000000;sunday=000000000000;input=4
got response:  {u'friday': u'000000000000', u'monday': u'000000000000', u'temp': u'0', u'tuesday': u'000000000000', u'thursday': u'000000000000', u'wednesday': u'000000000000', u'dwh_weather2': u'0', u'diff_under': u'10', u'sunday': u'000000000000', u'timer': u'0', u'input': u'4', u'dhw_remain': u'10', u'output': u'0', u'dwh_weather': u'0', u'saturday': u'000000000000'}
got serial:  2find controller retry 0 KeyError('Serial',)
ValueError('need more than 1 value to unpack',)
protocol_offline('controller offline',)
Looking for controller with S/N 55116
received data:    ghkcggfcha05511600650059Serial=55116;IP=0.0.0.0;Type=v13std;Ver=1016;Build=2;Lang=0
got response:  {u'Lang': u'0', u'Ver': u'1016', u'IP': u'0.0.0.0', u'Build': u'2', u'Serial': u'55116', u'Type': u'v13std'}
got serial:  55116
set xtea
set value k(B%qQUALA@}Wk
xtea encrypt 1
xtea encrypt 2
set error: 1
xtea_set uncertain, del key and use rsa 1632070769.3
ValueError('need more than 1 value to unpack',)
 use rsa for xtea set 3569
set valueD;f	w9N0ih5
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
set value k(B%qQUALA@}Wk
xtea encrypt 1
xtea encrypt 2
ValueError('need more than 1 value to unpack',)
KeyError('fan-regulation',) exc in getgroup regulation 1632070774.75
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',) exc in getgroup ignition-ignition_number 1632070775.61
 set value SBT/#_o
                  ;[3
xtea encrypt 1
xtea encrypt 2
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
KeyError('manual-output_up',) exc in getgroup output_up 1632070777.18
KeyError('fan-manual_mode',) exc in getgroup manual_mode 1632070777.41
KeyError('auger-output_exhaust',) exc in getgroup output_exhaust 1632070777.7
KeyError('boiler-forced_run',) exc in getgroup forced_run 1632070777.9
ValueError('need more than 1 value to unpack',)
KeyError('vacuum-temp',) exc in getgroup temp 1632070778.18
received data:    ghkcggfcha05511601850585monday=000000000000000000000000;tuesday=000000000000000000000000;wednesday=000000000000000000000000;thursday=000000000000000000000000;friday=000000000000000000000000;saturday=000000000000000000000000;sunday=000000000000000000000000;allweek=000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000;output_auger=0;output_vacuum=0;dutycycle_auger=100;minutes_pr_cm=15;max_time_out_of_range=30;total_hours=0;clear_alarm=0;min_distance=20;max_distance=80;distance_sensor=0
got response:  {u'allweek': u'000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000,000000000000000000000000', u'monday': u'000000000000000000000000', u'tuesday': u'000000000000000000000000', u'friday': u'000000000000000000000000', u'wednesday': u'000000000000000000000000', u'thursday': u'000000000000000000000000', u'clear_alarm': u'0', u'total_hours': u'0', u'sunday': u'000000000000000000000000', u'dutycycle_auger': u'100', u'output_auger': u'0', u'max_time_out_of_range': u'30', u'distance_sensor': u'0', u'max_distance': u'80', u'output_vacuum': u'0', u'minutes_pr_cm': u'15', u'saturday': u'000000000000000000000000', u'min_distance': u'20'}
got serial:  2find controller retry 0 KeyError('Serial',)
KeyError('operating_data-Serial',) exc in getgroup Serial 1632070778.68
KeyError('boiler-time',) exc in getgroup time 1632070778.98
ValueError('need more than 1 value to unpack',)
KeyError('manual-temp',) exc in getgroup temp 1632070779.19
KeyError('weather-manual_mode',) exc in getgroup manual_mode 1632070779.42
KeyError('auger-output_up',) exc in getgroup output_up 1632070779.71
KeyError('fan-forced_run',) exc in getgroup forced_run 1632070779.91
KeyError('operating_data-output_exhaust',) exc in getgroup output_exhaust 1632070780.19
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',) exc in getgroup operating_data-corr_medium 1632070780.78
received data:    ghkcggfcha05511604950951time=19/09-21 19:59:42;boiler_temp=64.2;smoke_temp=999.9;return_temp=999.9;t4_temp=999.9;t5_temp=6.0;t6_temp=27.8;t7_temp=999.9;distance=999;photo_level=63;shaft_temp=36.5;milli_ampere=315;oxygen=18.1;flow1=0;flow2=0;flow3=143;flow4=0;power_pct=12;power_kw=2.2;oxygen_ref=16.7;boiler_ref=65.0;mean_out_temp=7.7;dhw_ref=0.0;forward_ref=27.9;sun2_temp=999.9;sun_dhw_temp=999.9;sun_surplus_temp=999.9;pressure=0.00;air_flow=9990;sun_temp=999.9;house_valve_state=10;chill_out=7.7;sun_pumpspeed=0;sun_power_kw=0.0;cloud_level=100;forward_temp=27.8;back_pressure=21;t1_temp=0;air_quality=183;feed_low=272;feed_medium=80;feed_high=140;content=-7106;external_temp=6.0;state=5;substate=0;boiler_pump_state=1;dhw_valve_state=0;house_pump_state=1;sun_pump_state=0;sun_surplus_state=0;ashbox_minutes=2724.1;ashbox_contact=0.1;internet_uptime=100;off_on_alarm=1;contact1=0;contact2=0;dl_progress=0;substate_sec=0;corr_low=0;corr_medium=0;corr_high=2;ash_clean=15.2
got response:  {u'sun2_temp': u'999.9', u'forward_temp': u'27.8', u'off_on_alarm': u'1', u'power_kw': u'2.2', u'substate': u'0', u'dhw_ref': u'0.0', u'corr_low': u'0', u'flow4': u'0', u'external_temp': u'6.0', u'flow1': u'0', u'air_quality': u'183', u'flow3': u'143', u'flow2': u'0', u'feed_medium': u'80', u'return_temp': u'999.9', u't7_temp': u'999.9', u'sun_pumpspeed': u'0', u'sun_dhw_temp': u'999.9', u'milli_ampere': u'315', u'substate_sec': u'0', u'feed_high': u'140', u'chill_out': u'7.7', u'sun_temp': u'999.9', u'content': u'-7106', u'power_pct': u'12', u'air_flow': u'9990', u'forward_ref': u'27.9', u'back_pressure': u'21', u'internet_uptime': u'100', u'dhw_valve_state': u'0', u't1_temp': u'0', u'house_valve_state': u'10', u'contact2': u'0', u'state': u'5', u'ashbox_minutes': u'2724.1', u'oxygen_ref': u'16.7', u't5_temp': u'6.0', u'house_pump_state': u'1', u'corr_medium': u'0', u'dl_progress': u'0', u'smoke_temp': u'999.9', u'boiler_ref': u'65.0', u't6_temp': u'27.8', u'pressure': u'0.00', u'feed_low': u'272', u'shaft_temp': u'36.5', u'sun_surplus_temp': u'999.9', u'contact1': u'0', u'distance': u'999', u'boiler_temp': u'64.2', u'corr_high': u'2', u'sun_power_kw': u'0.0', u'oxygen': u'18.1', u'boiler_pump_state': u'1', u'photo_level': u'63', u'ash_clean': u'15.2', u't4_temp': u'999.9', u'sun_pump_state': u'0', u'ashbox_contact': u'0.1', u'cloud_level': u'100', u'time': u'19/09-21 19:59:42', u'mean_out_temp': u'7.7', u'sun_surplus_state': u'0'}
got serial:  2find controller retry 1 KeyError('Serial',)
KeyError('operating_data-Serial',) exc in getgroup Serial 1632070781.3
set value 9Md(r~}W(
xtea encrypt 1
xtea encrypt 2
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
KeyError('operating_data-temp',) exc in getgroup temp 1632070782.85
KeyError('weather2-time',) exc in getgroup time 1632070783.14
ValueError('need more than 1 value to unpack',)
received data:    ghkcggfcha05511601020364output_up=0;output_down=0;output_pump=0;active=0;avg_out_time=24;input_forward=0;chill_weight=0;gain_p=1.0;ref_1=16.0;ref_2=15.0;ref_3=10.0;ref_4=5.0;ref_5=0.0;ref_6=-5.0;ref_7=-10.0;temp_1=45.0;temp_2=45.0;temp_3=50.0;temp_4=55.0;temp_5=60.0;temp_6=65.0;temp_7=70.0;pow_1=0;pow_2=50;pow_3=100;pow_4=100;pow_5=100;pow_6=100;pow_7=100;input_reference=0;valvespin=45
got response:  {u'output_down': u'0', u'temp_5': u'60.0', u'temp_4': u'55.0', u'temp_7': u'70.0', u'temp_6': u'65.0', u'temp_1': u'45.0', u'temp_3': u'50.0', u'temp_2': u'45.0', u'output_pump': u'0', u'input_reference': u'0', u'pow_4': u'100', u'pow_6': u'100', u'pow_7': u'100', u'gain_p': u'1.0', u'pow_5': u'100', u'pow_2': u'50', u'pow_3': u'100', u'input_forward': u'0', u'output_up': u'0', u'pow_1': u'0', u'valvespin': u'45', u'ref_3': u'10.0', u'ref_2': u'15.0', u'ref_1': u'16.0', u'ref_7': u'-10.0', u'ref_6': u'-5.0', u'ref_5': u'0.0', u'ref_4': u'5.0', u'active': u'0', u'avg_out_time': u'24', u'chill_weight': u'0'}
got serial:  2find controller retry 2 KeyError('Serial',)
KeyError('ignition-Serial',) exc in getgroup Serial 1632070783.84
KeyError('hopper-pellets',) exc in getgroup pellets 1632070784.33
ValueError('need more than 1 value to unpack',)
KeyError('boiler-content',) exc in getgroup content 1632070784.6
KeyError('fan-temp',) exc in getgroup temp 1632070784.88
KeyError('regulation-output_exhaust',) exc in getgroup output_exhaust 1632070785.22
KeyError('boiler-boiler_gain_p',) exc in getgroup boiler_gain_p 1632070785.48
-------------------lost conn
KeyError('advanced_data-temp',) exc in getgroup temp 1632070785.75
ValueError('need more than 1 value to unpack',)
Looking for controller with S/N 55116
received data:    ghkcggfcha05511608110969210919,003709,9,2,0,0,%;210919,003709,1,0,2,5, ;210919,003408,2,16,19.9,0, ;210919,003318,1,0,43,2, ;210919,003302,9,13,0,0, ;210919,003247,9,11,0,0, ;210919,003247,2,1,0,0, ;210919,003247,2,22,0,0.0,C;210919,002644,2,4,0,0,%;210919,002644,9,6,0,0, ;210919,002644,9,4,0,0,%;210919,002644,1,0,5,43, ;210917,101646,1,0,2,5, ;210917,101326,0,506,130,122, ;210917,101325,2,16,20.1,0, ;210917,101235,1,0,9,2, ;210917,085642,1,0,5,9, ;210917,053215,1,0,2,5, ;210917,052922,0,506,129,130, ;210917,052921,2,16,20.1,0, ;210917,052831,1,0,9,2, ;210917,041642,1,0,5,9, ;210917,010800,1,0,2,5, ;210917,010510,0,506,138,129, ;210917,010509,2,16,20.1,0, ;210917,010419,1,0,9,2, ;210916,235212,1,0,5,9, ;210916,203002,1,0,2,5, ;210916,202708,0,506,111,138, ;210916,202707,2,16,20.1,0, ;210916,202617,1,0,9,2, ;210916,191133,1,0,5,9, ;210916,173844,9,2,0,0,%;210916,173844,1,0,2,5, ;210916,173533,2,16,19.9,0, ;210916,173438,1,0,43,2, ;210916,173422,9,13,0,0, ;210916,173407,9,11,0,0, 
2find controller retry 0 ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
Looking for controller with S/N 55116
received data:    ghkcggfcha05511600120059Serial=55116;IP=0.0.0.0;Type=v13std;Ver=1016;Build=2;Lang=0
got response:  {u'Lang': u'0', u'Ver': u'1016', u'IP': u'0.0.0.0', u'Build': u'2', u'Serial': u'55116', u'Type': u'v13std'}
got serial:  55116
set xtea
set value {ji:}!CVt,
xtea encrypt 1
xtea encrypt 2
set error: 1
xtea_set uncertain, del key and use rsa 1632070788.88
ValueError('need more than 1 value to unpack',)
ValueError('need more than 1 value to unpack',)
KeyError('oxygen-Serial',) exc in getgroup Serial 1632070790.06
KeyError('fan-regulation',) exc in getgroup regulation 1632070790.28
KeyError('ignition-output_exhaust',) exc in getgroup output_exhaust 1632070790.51
KeyError('weather2-pellets',) exc in getgroup pellets 1632070790.89
KeyError('operating_data-output_up',)use rsa for xtea set 3591 exc in getgroup
 output_up 1632070791.17
set value {ji:}!CVt,
ValueError('need more than 1 value to unpack',)
```

**Comment by motoz** [comment]
Looks like it can't write anything to the controller, you get repeated retries when it tries to write the xtea key (lighter chipher used after setting the xtea key using rsa encryption).
