### ISSUE TITLE
Pellmonsrv log repeating state change

### ISSUE THREAD

**Issue by Claws81** [motoz/PellMon#95]
Hi. Yesterday I noticed high activity in the log file of pellmonsrv.

it is currently repeating this endlessly:
```
2018-06-23 15:47:18,812 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-23 15:47:18,813 - INFO - state changed from Off to Stopped by external contact
2018-06-23 15:47:18,815 - INFO - state changed from Stopped by external contact to Off
2018-06-23 15:47:18,816 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-23 15:47:18,818 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:18,820 - INFO - state changed from Power to Stopped by external contact
2018-06-23 15:47:18,821 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:18,823 - INFO - state changed from Ignition 1 to Power
2018-06-23 15:47:18,824 - INFO - state changed from Stopped by external contact to Ignition 1
2018-06-23 15:47:19,831 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-23 15:47:19,833 - INFO - state changed from Off to Stopped by external contact
2018-06-23 15:47:19,835 - INFO - state changed from Stopped by external contact to Off
2018-06-23 15:47:19,838 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-23 15:47:19,841 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:19,843 - INFO - state changed from Power to Stopped by external contact
2018-06-23 15:47:19,845 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:19,847 - INFO - state changed from Ignition 1 to Power
2018-06-23 15:47:19,854 - INFO - state changed from Stopped by external contact to Ignition 1
2018-06-23 15:47:20,864 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-23 15:47:20,866 - INFO - state changed from Off to Stopped by external contact
2018-06-23 15:47:20,867 - INFO - state changed from Stopped by external contact to Off
2018-06-23 15:47:20,869 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-23 15:47:20,870 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:20,872 - INFO - state changed from Power to Stopped by external contact
2018-06-23 15:47:20,873 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:20,875 - INFO - state changed from Ignition 1 to Power
2018-06-23 15:47:20,876 - INFO - state changed from Stopped by external contact to Ignition 1
2018-06-23 15:47:21,883 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-23 15:47:21,886 - INFO - state changed from Off to Stopped by external contact
2018-06-23 15:47:21,889 - INFO - state changed from Stopped by external contact to Off
2018-06-23 15:47:21,891 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-23 15:47:21,892 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:21,894 - INFO - state changed from Power to Stopped by external contact
2018-06-23 15:47:21,895 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:21,897 - INFO - state changed from Ignition 1 to Power
2018-06-23 15:47:21,898 - INFO - state changed from Stopped by external contact to Ignition 1
2018-06-23 15:47:23,056 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-23 15:47:23,058 - INFO - state changed from Off to Stopped by external contact
2018-06-23 15:47:23,059 - INFO - state changed from Stopped by external contact to Off
2018-06-23 15:47:23,060 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-23 15:47:23,061 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:23,062 - INFO - state changed from Power to Stopped by external contact
2018-06-23 15:47:23,063 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:23,064 - INFO - state changed from Ignition 1 to Power
2018-06-23 15:47:23,065 - INFO - state changed from Stopped by external contact to Ignition 1
```
I have tried restarting all of Pellmon and the burner, to no avail.
On Stokercloud the state remain on 'stopped by external contact' as well as on the burner, so I suspect it is Pellmon that is misbehaving.

I have turned on the burner via the external contact, and it responds as it should, both on the burner and Stokercloud, but the log output remains the same.

Any idea of what causes this? 
Pellmon is install on the system and not run from source folder.

**Comment by motoz** [comment]
The problem probably lies somewhere here https://github.com/motoz/PellMon/blob/3e2511ada9e2cd5715c5c9ad67f45a41ef8d82f3/src/Pellmonsrv/plugins/nbecom/__init__.py#L227

The controller maintains an internal event log, which can be read from the item 'event_id_list'. Pellmon polls this item and logs new events in this list. To keep track of which events have already been logged to pellmon's event log, the contents of that is copied to another item, 'logged_event_id_list' after they have been logged. You can read both using pellmoncli, 'pellmocli get event_id_list'.

Looks like they somehow don't end up in the 'logged_event_id_list' item, the contents of those two should be identical.

**Comment by motoz** [comment]
After letting this sink in for a while I noticed that this sequence of events is repeated about every second:
2018-06-23 15:47:20,864 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-23 15:47:20,866 - INFO - state changed from Off to Stopped by external contact
2018-06-23 15:47:20,867 - INFO - state changed from Stopped by external contact to Off
2018-06-23 15:47:20,869 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-23 15:47:20,870 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:20,872 - INFO - state changed from Power to Stopped by external contact
2018-06-23 15:47:20,873 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-23 15:47:20,875 - INFO - state changed from Ignition 1 to Power
2018-06-23 15:47:20,876 - INFO - state changed from Stopped by external contact to Ignition 1

The eventlogger thread probably gets an exception right after logging the "state changed from Stopped by external contact to Ignition 1" event, which is then caught and ignored, and at the same time self.db['logged_event_id_list'].value = ';'.join(events)
is skipped, so it doesn't know that the events were already logged the next loop. Can you get the contents of 'event_id_list' with pellmoncli? There could be something interesting right after that last logged event in the loop. And if you run pellmonsrv in foreground mode you should be able to see something printed from the caught exception.

**Comment by Claws81** [comment]
Phew, Pellmon hasn't worked at all for the last two days. I wonder if a system update has messed something up.

Finally I am back to the issue I had the other day.

This is the output of 'get event_id_list'

`180623,164511,2,1,0,0, ;180623,164511,2,4,0,0, ;180623,164511,1,0,5,24, ;180623,160231,1,0,2,5, ;180623,155851,1,0,24,2, ;180623,144542,2,0,13,640, ;180622,221952,1,0,14,24, ;180622,215912,1,0,24,14, ;180622,103044,2,1,0,0, ;180622,103044,2,4,0,0, ;180622,103044,1,0,5,24, ;180622,095012,2,4,0,0, ;180622,054836,1,0,2,5, ;180622,054502,1,0,24,2, ;180527,114809,2,0,13,640, ;180525,204947,2,0,13,640, ;180522,080222,2,1,0,0, ;180522,080222,2,4,0,0, ;180522,080222,1,0,5,24, ;180522,072116,2,4,0,0, ;180522,025831,1,0,2,5, ;180522,025502,1,0,24,2, ;180520,084530,2,1,0,0, ;180520,084530,2,4,0,0, ;180520,084530,1,0,5,24, ;180520,042350,1,0,2,5, ;180520,042036,1,0,24,2, ;180519,103016,2,1,0,0, ;180519,103016,2,4,0,0, ;180519,103016,1,0,5,24, ;180519,082312,2,4,0,0, ;180519,034455,1,0,2,5, ;180519,034205,1,0,24,2, ;180517,095235,2,1,0,0, ;180517,095235,2,4,0,0, ;180517,095235,1,0,5,24, ;180517,072156,2,4,0,0, ;180517,025609,1,0,2,5, ;180517,025256,1,0,24,2, ;180514,083011,2,1,0,0, ;`


Edit 1:  removed
Edit 2: So, it is confirmed that this behavior only happens when Pellmon is run in 'system mode'
I now have both srv and web running in the foreground as a user, and there's not log input apart from pellmonsrv starting and exiting while I test.

**Comment by Claws81** [comment]
By the way, this is the browser output from pellmonweb when run as user (pellmonsrv too)
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/pi/PellMon/src/Pellmonweb/pellmonweb.py", line 678, in index
    return tmpl.render(username=cherrypy.session.get('_cp_username'), empty=False, autorefresh=autorefresh, timeSeconds = timeSeconds, timeChoices=timeChoices, timeNames=timeNames, timeChoice=timespan, graphlines=graph_lines, selectedlines = lines, timeName = timeName, websockets=websockets, webroot=cherrypy.request.script_name, widgets = widgets, version = __version__, rand=self.rand)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "layout_html", line 93, in render_body
  File "index_html", line 51, in render_body
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 761, in _include_file
    callable_(ctx, **kwargs)
  File "graph", line 36, in render_body
IndexError: list index out of range
```

**Comment by motoz** [comment]
Can you give me the contents of logged_event_id_list also?

**Comment by Claws81** [comment]
From logged_event_id_list:
`180623,164511,2,1,0,0, ;180623,164511,2,4,0,0, ;180623,164511,1,0,5,24, ;180623,160231,1,0,2,5, ;180623,155851,1,0,24,2, ;180623,144542,2,0,13,640, ;180622,221952,1,0,14,24, ;180622,215912,1,0,24,14, ;180622,103044,2,1,0,0, ;180622,103044,2,4,0,0, ;180622,103044,1,0,5,24, ;180622,095012,2,4,0,0, ;180622,054836,1,0,2,5, ;180622,054502,1,0,24,2, ;180527,114809,2,0,13,640, ;180525,204947,2,0,13,640, ;180522,080222,2,1,0,0, ;180522,080222,2,4,0,0, ;180522,080222,1,0,5,24, ;180522,072116,2,4,0,0, ;180522,025831,1,0,2,5, ;180522,025502,1,0,24,2, ;180520,084530,2,1,0,0, ;180520,084530,2,4,0,0, ;180520,084530,1,0,5,24, ;180520,042350,1,0,2,5, ;180520,042036,1,0,24,2, ;180519,103016,2,1,0,0, ;180519,103016,2,4,0,0, ;180519,103016,1,0,5,24, ;180519,082312,2,4,0,0, ;180519,034455,1,0,2,5, ;180519,034205,1,0,24,2, ;180517,095235,2,1,0,0, ;180517,095235,2,4,0,0, ;180517,095235,1,0,5,24, ;180517,072156,2,4,0,0, ;180517,025609,1,0,2,5, ;180517,025256,1,0,24,2, ;180514,083011,2,1,0,0, ;
`

**Comment by Claws81** [comment]
Strange - now I started it again, but this time as system, now after a few burps, it hasn't logged anything new.
Pellmon via web seems to be working normally so far.

```

2018-06-28 17:43:40,737 - INFO - state changed from Stopped by external contact to Ignition 1
--
2018-06-28 17:43:40,736 - INFO - state changed from Ignition 1 to Power
2018-06-28 17:43:40,735 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-28 17:43:40,733 - INFO - state changed from Power to Stopped by external contact
2018-06-28 17:43:40,732 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-28 17:43:40,730 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-28 17:43:40,729 - INFO - state changed from Stopped by external contact to Off
2018-06-28 17:43:40,727 - INFO - state changed from Off to Stopped by external contact
2018-06-28 17:43:40,725 - INFO - type: 2, id: 0, v1: 13, v2: 640
2018-06-28 17:43:40,724 - INFO - state changed from Stopped by external contact to Ignition 1
2018-06-28 17:43:40,722 - INFO - state changed from Ignition 1 to Power
2018-06-28 17:43:40,720 - INFO - state changed from Power to Stopped by external contact
2018-06-28 17:43:40,718 - INFO - type: 2, id: 4, v1: 0, v2: 0
2018-06-28 17:43:40,707 - INFO - type: 2, id: 1, v1: 0, v2: 0
2018-06-28 17:43:36,644 - INFO - Connected to S/N 24706 on 10.0.0.23
2018-06-28 17:43:35,719 - INFO - copied /home/pi/PellMon/src/dev_var/lib/pellmon/nvrrd.db to /mnt/ramdisk/rrd.db
2018-06-28 17:43:35,637 - INFO - Activated plugins: SiloLevel, Consumption, Cleaning, NBEcom
2018-06-28 17:43:35,128 - INFO - Looking for plugins in /usr/local/lib/python2.7/dist-packages/Pellmonsrv/plugins
2018-06-28 17:43:35,125 - INFO - starting PellMon


```

**Comment by motoz** [comment]
Yes, when logged_event_id_list is identical with event_id_list, it shouldn't log any new events. Hard to say what caused it since it has stopped.

**Comment by Claws81** [comment]
No new logged items since yesterday, so I guess it was a passing thing for some reason.
I'll revisit if it starts acting up again - thanks :)
